build:backend:
  image: python:3.7
  cache:
    paths:
    - ~/.cache/pip/
  script:
  - python -V
  - pip install pipenv
  - pipenv install --dev
  - pipenv run python3 -m pytest tests/ --cov=. --cov-report xml:coverage.xml --disable-warnings
  - pipenv run python-codacy-coverage -r coverage.xml
